/**
 * Curated NSE symbol pools for each market-cap category.
 * The top-screener route samples from these lists.
 */

export const LARGE_CAP: string[] = [
  'RELIANCE','TCS','HDFCBANK','BHARTIARTL','ICICIBANK','INFOSYS','SBIN','LICI',
  'HINDUNILVR','ITC','BAJFINANCE','LT','KOTAKBANK','AXISBANK','MARUTI',
  'ASIANPAINT','NESTLEIND','HCLTECH','WIPRO','ULTRACEMCO','TITAN','POWERGRID',
  'NTPC','ONGC','COALINDIA','TECHM','BAJAJ-AUTO','ADANIENT','ADANIPORTS',
  'GRASIM','SUNPHARMA','CIPLA','DRREDDY','DIVISLAB','TATAMOTORS','TATASTEEL',
  'JSWSTEEL','HINDALCO','INDUSINDBK','SHREECEM',
];

export const MID_CAP: string[] = [
  'PERSISTENT','COFORGE','LTTS','MPHASIS','TATATECH','DIXON','ABCAPITAL',
  'CAMS','ANGELONE','IIFL','AARTIIND','PIIND','METROPOLIS','LALPATHLAB',
  'CONCOR','NAVINFLUOR','ALKYLAMINE','CLEAN','DEEPAKNTR','FINEORG',
  'POLYMED','ASTERDM','MAXHEALTH','YATHARTH','TIPSMUSIC','MAPMYINDIA',
  'EASEMYTRIP','ROUTE','DEVYANI','SAPPHIRE',
];

export const SMALL_CAP: string[] = [
  'SAFARI','CAMPUS','HAPPYMIND','IDEAFORGE','INOXGREEN','LATENTVIEW',
  'DATAMATICS','TANLAPLATF','BIRLASOFT','MASTEK','NIITLTD','CMSINFO',
  'MSTCLTD','RAILTEL','IRCTC','CAMLINFINE','AAVAS','CREDITACC','FUSION',
  'UJJIVAN','SURYODAY','EQUITASBNK','UTKARSHBNK','ESAFSFB',
  'JINDALSAW','RATNAMANI','WELCORP','MAHSEAMLES','APL','RAMCOCEM',
];

export const MICRO_CAP: string[] = [
  'EXICOM','AZAD','UNIPARTS','KAYNES','SYRMA','AVALON','PCBL','RPGLIFE',
  'GREENPANEL','ACRYSIL','HLEGLAS','VINYLINDIA','VINDHYATEL','TECHNOE',
  'SHIVALIK','TEXRAIL','IRCON','RVNL','STLTECH','TBOTEK',
  'ZAGGLE','IDEAFORGE','ANANTRAJ','PRITI','NOVARTIND',
];
